### ISSUE TITLE
Artifacts when zooming out

### ISSUE THREAD

**Issue by matthewturk** [yt-project/widgyts#21]
If we zoom out past the left and right edges, the image array doesn't get overwritten, leaving lots of artifacts.  We could fix this by clearing the image, but the most common use case is when we zoom past limits, so we could also disable that.

**Comment by munkm** [comment]
Disabling zooming out past the bounds is a good idea, but what if our canvas is square but the data array/image array isn't? We might have a use case where we zoom out to the edge of the array that's wider and still see artifacts from the shorter edge.

**Comment by munkm** [comment]
Maybe we could make it so we only clear the image when the canvas width is greater than one of the array bounds and also disable zooming past the largest array bounds?

**Comment by MatthewTurk** [comment]
Yup, that'd work!
