### ISSUE TITLE
Do performance analysis of widgyts

### ISSUE THREAD

**Issue by munkm** [yt-project/widgyts#39]
We have presented widgyts to the community, but we need to do some characterization of how it performs at different scales as compared to traditional server-side visualization. I propose using three differently-sized datasets with widgyts, and then showing the turnover between client vs. server-based viz with each of them. We'll do this by showing the number of interactions it takes to make it worthwhile to load the dataset to the client, and then show the latency of visualization as everything scales.

**Comment by MatthewTurk** [comment]
I think that it would also be worthwhile to characterize this in terms of latency and UI responsiveness, with a citation to something like [this paper](https://idl.cs.washington.edu/papers/latency/).

This can also probably be measured using chrome's performance measurements.

I think this could be a reasonably small portion of the paper and shouldn't hang up the rest of the text.

**Comment by munkm** [comment]
I think the main performance-dependent things we need to highlight are: 
- poor connectivity to a server impacts interactive viz
- variable resolution data (that might be sparse in some regions) may generate more data in a FRB before it's pushed client-side than if it's loaded in its original form to a client. 
- the fact that the computations are client-side means that this can be embedded.
