### ISSUE TITLE
Use IPython built-in registration instead of monkey patching

### ISSUE THREAD

**Issue by matthewturk** [yt-project/widgyts#48]
Instead of monkey-patching for `display`, we should make a registered representation method:

https://ipython.readthedocs.io/en/stable/config/integrating.html#formatters-for-third-party-types

**Comment by munkm** [comment]
👍 I definitely support this.

**Comment by matthewturk** [comment]
On reviewing, I'm not sure that this actually will work.  It lets you register formatters, but we actually are registering display hooks.  We don't want to actually output HTML, but instead widgets, and so I'm not completely sure that it applies.  I'd like to see `_ipython_display_` get used more for our objects, but this seems to be a different direction.
