### ISSUE TITLE
Update for new ipycanvas

### ISSUE THREAD

**Issue by matthewturk** [yt-project/widgyts#55]
We need to make sure we're up to date for https://github.com/martinRenou/ipycanvas/pull/111 where the way the layout and image sizes are affected once #53 goes in.

**Comment by martinRenou** [comment]
Note that the default behavior of ipycanvas should not change. You might see ipycanvas behavior changes only if you manipulate the `layout` property.

**Comment by matthewturk** [comment]
@martinRenou Thanks!  What I want to check is that we're also getting our image size correct, since we supply that in the browser to a callback to generate the data.  It's entirely possible we're doing everything as we should, but I just wanted to make a note in case we weren't.  :grin:
